spring:
  datasource:
    url: jdbc:mariadb://${testDbIp:127.0.0.1}:3306/app__2022_10_11__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${testDbId:root}
    password: ${testDbPw:}
  jpa:
    hibernate:
      ddl-auto: create